# Generated by Django 5.0.6 on 2024-08-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("create", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="category",
            field=models.ManyToManyField(to="restaurant_app.category"),
        ),
    ]
