# Generated by Django 5.1 on 2024-08-29 11:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_category_alter_restaurant_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='create',
        ),
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
