# Generated by Django 5.0.6 on 2024-08-23 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0002_order_delivery_cost_alter_order_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="oorderitem",
                to="order_app.order",
            ),
        ),
    ]
