# Generated by Django 5.1 on 2024-09-11 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='discount_spachial',
            new_name='discount_special',
        ),
    ]
