# Generated by Django 5.0.6 on 2024-08-23 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="frate",
                to="food_app.food",
            ),
        ),
    ]
