# Generated by Django 5.0.6 on 2024-08-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_app", "0002_alter_rate_food"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="created",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="food",
            name="update",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
