# Generated by Django 5.0.6 on 2024-08-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_app", "0003_alter_food_created_alter_food_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="discount_spachial",
            field=models.BooleanField(default=False),
        ),
    ]
