# Generated by Django 5.0.6 on 2024-08-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_app", "0004_food_discount_spachial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="category",
        ),
        migrations.AddField(
            model_name="food",
            name="category",
            field=models.ManyToManyField(to="food_app.category"),
        ),
    ]
