# Generated by Django 5.1 on 2024-08-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0005_remove_food_category_food_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='discount_spachial',
            new_name='discount_special',
        ),
        migrations.AlterField(
            model_name='food',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='discount_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
