# Generated by Django 5.1 on 2024-08-29 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0006_rename_discount_spachial_food_discount_special_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='discount_special',
            new_name='discount_spachial',
        ),
    ]
